# ============================================================
# 图书管理系统 - 后端配置文件
# ============================================================

server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/free_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

fileBaseUrl: http://localhost:9090

# JWT accessToken
jwt:
  secret: "oaj4HKxnulJxql2sw8o6gPe2m3oMzKZJAJezYweNUvRB9yPl5fABVHEbWoAu0za9"
  expire-ms: 86400000

# RSA（登录/注册/改密密码传输加密，前端用公钥加密，后端私钥解密）
rsa:
  private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyAy+Fb653UKZJc9uZ+yjl9uixH1z/h0BR6bxtCpOvBYJaA5myoTZzl2egTSthEbiIFUuNWXn8/9E9BaRE0Z8B59Tu5JYqaHlICKND/pdHDmEEOBuEJ205U63qxY7FX6WwK+XwQHq7CGsF688a+QCvh4KGgue4LZYFjwgDb24lOAPq3Dq0G8wjmCI+4veLDTVeVUa1ZuD4Y1NpGVQ63cNekw8f6Gm7c3dwTnCjbz5RpDpOpnsIMWRv/ZlOBKPdhxKiwrQkdi1h2ynMPBIAFdhZxR8WiSPErqgIqjZKG82/gJvqvzmt9hiCQEbUyXhEHIZvgJrvGT6c1GDVE9i4LPoRAgMBAAECggEABLSFWclPKvuwfYIItKv5E4UAdwgNcPqd9lxPfPFZ4HcskB0Gv7w3oHwIwumvQxhREJXBgrmx+gA4A10mD6Sbx5TdYbgciP/sbr09tYMh9ACbC13BSm+xWSHPV8SDhs+FpV+vqvdFVzK8g3JNbdjVjg4uosgMgGeCDuEONOsJ1gV26qfPinMmSdxg6tS2ZK5Dun94bOEt09DUL6sYdVnTJgVQlF1TDpDhRVzQJn3p6hHPEcAx0ZYRfGdkX3B6paWOTGLckOJjNGWPddhCO24GThjKip/Y9Q9eGTVUgUSPR+184t4PgtY7qMx3I/p6M5kS18OqGLWXKyNIbCBwqFKafQKBgQDsrsm9h78XvvMQLKwQ3yP0960K9nnq7EokPKQHLtu3jGz/yq0bQrdhgOMbh4HXUD//FTXJ1/wF+1V7Z4ebGmQCr7RBVnhrMdzqwTXp990hJ//Z31ij7j6qsvR2JvfR6TfBbqYeGY+eq9K4nBhc1UVWYPANMOYwIzI7XCwsVTCuVQKBgQDAioyanipGXayae33qWFDJw9fLYLKOOrOLihyvcUXEwmDKGzQTofBjfIEXgv9otRoF3YQdlXUqEfRep6o05PMdQjVcHsyk2N8yFscKe/kPQZG/OWwxOtiZA8YfhI7cnpElzWypNaJdwPsRf96im52Y7x9VkQYJhw1RfRAywgvgzQKBgQCiXAC+SEmZI38foFVkuX20BNcqxwu5UOBHXWX0G3vTvLvk+IapRaoAc+bXMqyqJD3SYR1l2gjjnZb1MX7/sinbAeb4TzYJ6smuLF4sosCJhyPmtGTdB4jrlhlGl9K2p3J8+cdwrH4uDZZe142K2S5YY+UoV1wAt5Q0zjTrMIFVhQKBgADlZCwgClBThUcexgI+MPoPaESxCYOx8D35AZMrcsisouit4bspqMW9wZgLawbguONIGaJNnML6XGnIW/ltC1iag0cPeaJWxAsmofyBgTI5+uSp7r/35yQnKVfiNQv/zOshHp1W+492I3T8ZFvbX4tjqYCrcRzAPSag719dGdMNAoGAa2IjlnTcHAVmjdNSvJ+sS1l9m/QTvnTvNv+W4Aa34TjTApI0mTvQkk3OjZTRGTpgxrN9zA0LcUjzKJ8tDOIzY1gv3ROlpiV8FUE7BRPfR+DJ+Yc2zlAYouiA7zgTBGL7ewMC1d1rY0czMgNT2fgsqkE5KdvDaLJssZLZ2X3EK1g="
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsgMvhW+ud1CmSXPbmfso5fbosR9c/4dAUem8bQqTrwWCWgOZsqE2c5dnoE0rYRG4iBVLjVl5/P/RPQWkRNGfAefU7uSWKmh5SAijQ/6XRw5hBDgbhCdtOVOt6sWOxV+lsCvl8EB6uwhrBevPGvkAr4eChoLnuC2WBY8IA29uJTgD6tw6tBvMI5giPuL3iw01XlVGtWbg+GNTaRlUOt3DXpMPH+hpu3N3cE5wo28+UaQ6TqZ7CDFkb/2ZTgSj3YcSosK0JHYtYdspzDwSABXYWcUfFokjxK6oCKo2ShvNv4Cb6r85rfYYgkBG1Ml4RByGb4Ca7xk+nNRg1RPYuCz6EQIDAQAB"
